version: "3.5"
networks:
  traefik_proxy:
    external: true
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 2G
        reservations:
          cpus: "1.00"
          memory: 1G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    # Disables the user namespace for this container.
    userns_mode: "host"
    restart: on-failure:5
    # If user namespaces is enabled, disable 'domainname' to avoid
    # permission errors.
    domainname: ${EXTERNAL_DOMAIN}
    hostname: nextcloud
    networks:
      - traefik_proxy
      - internal
    volumes:
      - ${DOCKER_DIR}/nextcloud/config:/config
      - ${DOCKER_DIR}/nextcloud/data:/data
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      # HTTP router - 'nextcloud-rtr'.
      - "traefik.http.routers.nextcloud-rtr.entrypoints=https"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`nextcloud.$EXTERNAL_DOMAIN`)"
      - "traefik.http.routers.nextcloud-rtr.tls=true"
      # HTTP service - 'nextcloud-svc'.
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      # Force Traefik to use https over port 443.
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=443"
      # Middlewares
      - "traefik.http.routers.nextcloud-rtr.middlewares=chain-nextcloud@file"
      #- "traefik.http.routers.nextcloud-rtr.middlewares=chain-no-auth@file"    # No authentication.
      #- "traefik.http.routers.nextcloud-rtr.middlewares=chain-basic-auth@file" # Basic authentication.
  nextcloud-db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud-db
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 1G
        reservations:
          cpus: "1.00"
          memory: 512M
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    # Disables the user namespace for this container.
    userns_mode: "host"
    restart: on-failure:5
    hostname: nextcloud-db
    networks:
      - internal
    volumes:
      - ${DOCKER_DIR}/nextcloud/db:/config
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.50"
          memory: 256M
    cap_drop:
      - ALL
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    # Disables the user namespace for this container.
    userns_mode: "host"
    user: "${CONTAINER_UID}:${CONTAINER_GID}"
    restart: on-failure:5
    hostname: nextcloud-redis
    networks:
      - internal
    read_only: true
    volumes:
      - ${DOCKER_DIR}/nextcloud/redis:/data
    sysctls:
      # Fix warning message according to the following reported issue:
      # https://github.com/docker-library/redis/issues/35
      net.core.somaxconn: "511"
